# .github/workflows/dotnet.yml

name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Staff/Staff.sln

    - name: Build
      run: dotnet build Staff/Staff.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test Staff/Staff.Test/Staff.Tests.csproj --no-build --verbosity normal
